apiVersion: v1
kind: Service
metadata:
  name: app42
  labels:
    app: app42
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: app42
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app42
  labels:
    app: app42
  namespace: default
spec:
  selector:
    matchLabels:
      app: app42
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app42
        tier: frontend
    spec:
      containers:
      - image: abegorov/app42:{{VERSION}}
        name: app42
        ports:
        - containerPort: 8080
          name: app42
