apiVersion: v1
kind: Service
metadata:
  name: "{{DB_HOST}}"
  labels:
    app: app42
spec:
  ports:
    - port: 3306
  selector:
    app: app42
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: app42
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app42-db
  labels:
    app: app42
spec:
  selector:
    matchLabels:
      app: app42
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app42
        tier: mysql
    spec:
      containers:
      - image: mariadb:latest
        name: mariadb
        env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
          - name: MYSQL_DATABASE
            value: "{{DB_NAME}}"
          - name: MYSQL_USER
            value: "{{DB_USER}}"
          - name: MYSQL_PASSWORD
            value: "{{DB_PASSWORD}}"
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
